const skills = [
  "React JS",
  "NextJs",
  "React Native",
  "NodeJS",
  "JavaScript",
  "REST APIs",
  "CI/CD",
  "JSON",
  "Redux",
  "Zustand",
  "React Hook Form",
  "Git/Github",
  "Linux",
  "Express JS",
  "UI Design",
  "Component Libraries",
  "Fluent in Spanish",
  "SQL",
  "PostgreSQL",
  "MongoDB",
  "Firebase",
  "Supabase",
  "GraphQL",
  "TypeScript",
  "Zod",
  "Material UI",
  "Radix Primitives",
  "SASS",
  "HTML5/CSS",
  "Emotion JS",
  "Styled Components",
  "Storybook",
  "Docker",
  "AWS",
  "Vercel",
  "Travis CI",
  "PHP",
  "Web sockets",
  "APIs",
  "Jest",
  "React Testing Library",
  "Content Management Systems (CMS)",
];

export default skills;
