import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import About from "../components/home/about/about";
import Jumbo from "../components/home/jumbo/jumbo";
import Work from "../components/home/work/work";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Jumbo />
        <Work />
        <About />
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
